# Generated by Django 5.2.1 on 2025-05-21 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_employees'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employees',
            new_name='Students',
        ),
    ]
