# Generated by Django 5.2.1 on 2025-06-07 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_employees_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='address',
            field=models.CharField(default='Pune', max_length=50),
        ),
    ]
